import {
  FaBook,
  FaCalendar,
  FaChalkboard,
  FaCog,
  FaFileInvoice,
  FaHome,
  FaMoneyBillAlt,
  FaMoneyCheckAlt,
  FaNetworkWired,
  FaPhone,
  FaPizzaSlice,
  FaRegFileAlt,
  FaRegFrown,
  FaThermometerHalf,
  FaVirusSlash,
} from "react-icons/fa";

export const iconMap = {
  filealt: FaRegFileAlt,
  invoice: FaFileInvoice,
  pizza: FaPizzaSlice,
  chalkboard: FaChalkboard,
  phone: FaPhone,
  network: FaNetworkWired,
  halfthermometer: FaThermometerHalf,
  virusslash: FaVirusSlash,
  calendar: FaCalendar,
  book: FaBook,
  moneycheckalt: FaMoneyCheckAlt,
  cog: FaCog,
  frown: FaRegFrown,
  moneybillalt: FaMoneyBillAlt,
  home: FaHome,
};
export type IconId = keyof typeof iconMap;
