import "./globals.css";

import { NavRail } from "@/app/nav-rail";
import { ThemeProvider } from "@/components/providers/theme-provider";
import type { Metadata } from "next";
import { Figtree, Inter, JetBrains_Mono } from "next/font/google";

const inter = Inter({ subsets: ["latin"], display: "swap", variable: "--font-inter" });
const jetbrains = JetBrains_Mono({ subsets: ["latin"], variable: "--font-jetbrains" });
const figtree = Figtree({ subsets: ["latin"], variable: "--font-figtree" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrains.variable} ${figtree.variable} font-sans h-full text-gray-800 dark:text-gray-300 flex`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange>
          <NavRail />
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
